version: "3"
services:
  app:
    image: snipe/snipe-it:${SOFTWARE_VERSION_TAG}
    restart: always
    volumes:
      - ./storage:/var/lib/snipeit
    ports:
      - "172.17.0.1:15685:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env

  db:
    image: mariadb:10.6.4-focal
    restart: always
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$DB_USERNAME --password=$$DB_PASSWORD
      interval: 5s
      timeout: 1s
      retries: 5
    ports:
      - "172.17.0.1:53465:3306"

  pma:
    image: elestio/phpmyadmin
    restart: always
    links:
      - db:db
    ports:
      - "172.17.0.1:16864:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${DB_PASSWORD}
      UPLOAD_LIMIT: 500M
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    depends_on:
      - db
